# Generated by Django 4.2.1 on 2023-05-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='lien_linkedIn',
            new_name='profil_linkedin_ou_site_personnel',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='ficher',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.AddField(
            model_name='personnel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_affectation',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photosProfil/'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
