# Generated by Django 4.2.1 on 2023-05-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0003_rename_lien_linkedin_personnel_profil_linkedin_ou_site_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
                ('FichierProjet', models.FileField(blank=True, null=True, upload_to='FichierProjet/')),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.equipe')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
