# Generated by Django 4.2.1 on 2023-05-22 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0008_demandeprojet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='FichierProjet',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='services',
        ),
        migrations.AddField(
            model_name='projet',
            name='acheve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.client'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='projet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='libelle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='projet',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.equipe'),
        ),
    ]
